services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${DATABASE_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      # default is:
      #- '3306:3306'
      - ${DATABASE_PORT}:3306
    expose:
      # Opens port 3306 on the container
      # default is:
      #- '3306'
      - '${DATABASE_PORT}'
    volumes:
      - api-db:/var/lib/mysql
    env_file:
      - .env

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    expose:
      - 1080
      - 1025
    # ports:
    #   - ${MAIL_CLIENT_PORT}:1080
    #   - ${MAIL_PORT}:1025

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test

volumes:
  api-db:
    driver: local
